export const cardConstants = {
    GET_CHART_DATA_REQUEST: 'GET_CHART_DATA_REQUEST',
    GET_CHART_DATA_SUCCESS: 'GET_CHART_DATA_SUCCESS',
    GET_CHART_DATA_FAILURE: 'GET_CHART_DATA_FAILURE',

    GET_ITEM_LIST_REQUEST: 'GET_ITEM_LIST_REQUEST',
    GET_ITEM_LIST_SUCCESS: 'GET_ITEM_LIST_SUCCESS',
    GET_ITEM_LIST_FAILURE: 'GET_ITEM_LIST_FAILURE', 

    CHANGE_REFRESH_TIME: 'CHANGE_REFRESH_TIME'
};
